theme: minima
baseurl: "/Blog"
title: "Rae's Blog"
description: "Self-taught CS explorer sharing my journey through algorithms, systems, and code. Building knowledge brick by brick and documenting the ride."
minima:
  show_excerpts: true
  social_links:
    twitter: SolTae_
    github: Rae699
