theme: minima
baseurl: "/Blog"
title: "Remy C."
description: "Self-taught CS explorer sharing my journey through algorithms, systems, and code. Building knowledge brick by brick and documenting the ride."

# Social links
social_links:
  - name: "Twitter"
    url: "https://twitter.com/SolTae_"
  - name: "GitHub"
    url: "https://github.com/Rae699"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/remy-charras/" 


# Theme settings
minima:
  show_excerpts: true


