theme: minima
title: "Remy C."
baseurl: "/Blog"
description: "Self-taught CS explorer sharing my journey through algorithms, systems, and code. Building knowledge brick by brick and documenting the ride. Currently grinding in hard mode."

# Social links
twitter_username: SolTae_
github_username: Rae699
linkedin_username: remy-charras

# Theme settings
minima:
  date_format: "%b %-d, %Y"
  show_excerpts: true
  future: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Header pages
header_pages:
  - table-of-contents.md
  - about.md
  - start-here.md


